// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type User struct {
	ID       *int32
	Email    string
	Password string
	Name     string
	Gender   string
	Age      int32
}
