// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into users (email, password, name, gender, age)
values ($1, $2, $3, $4, $5)
returning id, email, password, name, gender, age
`

type CreateUserParams struct {
	Email    string
	Password string
	Name     string
	Gender   string
	Age      int32
}

func (q *Queries) CreateUser(ctx context.Context, arg User) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Password,
		arg.Name,
		arg.Gender,
		arg.Age,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Gender,
		&i.Age,
	)
	return i, err
}
